
#Gobber Lucky Block Generation
[gobber2_lucky_block]
	#Size of Gobber Lucky Block pockets [3-100, default: 4]
	#Range: 3 ~ 100
	gobberLuckyBlockSize = 3
	#Chances of Gobber Lucky Block pocket being generated [0-30, default: 20]
	#Range: 0 ~ 30
	gobberLuckyBlockChance = 2
	#Minimal height for Gobber Lucky Block pocket generation, [-64 to -384, default: -40]
	#Range: -64 ~ 384
	gobberLuckyBlockMinHeight = -40
	#Maximal height for Gobber Lucky Block pocket generation [-64 to -384, default: 255]
	#Range: -64 ~ 384
	gobberLuckyBlockMaxHeight = 255

#Gobber Lucky Block Nether Generation
[gobber2_lucky_block_nether]
	#Size of Gobber Lucky Block Nether pockets [3-100, default: 4]
	#Range: 3 ~ 100
	gobberLuckyBlockNetherSize = 3
	#Chances of Gobber Lucky Block Nether pocket being generated [0-30, default: 20]
	#Range: 0 ~ 30
	gobberLuckyBlockNetherChance = 5
	#Minimal height for Gobber Lucky Block Nether pocket generation, [0-255, default: 1]
	#Range: 0 ~ 255
	gobberLuckyBlockNetherMinHeight = 1
	#Maximal height for Gobber Lucky Block Nether pocket generation [0-255, default: 255]
	#Range: 0 ~ 255
	gobberLuckyBlockNetherMaxHeight = 255

#Gobber Ore Generation
[gobber2_ore]
	#Size of Gobber Ore pockets [3-100, default: 4]
	#Range: 3 ~ 100
	gobberOreSize = 6
	#Chances of Gobber Ore pocket being generated [0-30, default: 15]
	#Range: 0 ~ 30
	gobberOreChance = 4
	#Minimal height for Gobber Ore pocket generation, [-64 to -255, default: -40]
	#Range: -64 ~ 384
	gobberOreMinHeight = -40
	#Maximal height for Gobber Ore pocket generation [-64 to -255, default: 15]
	#Range: -64 ~ 384
	gobberOreMaxHeight = 15

#Gobber Nether Ore Generation
[gobber2_ore_nether]
	#Size of Gobber Nether Ore pockets [3-100, default: 3]
	#Range: 3 ~ 100
	gobberOreNetherSize = 6
	#Chances of Gobber Nether Ore pocket being generated [0-30, default: 15]
	#Range: 0 ~ 30
	gobberOreNetherChance = 4
	#Minimal height for Gobber Nether Ore pocket generation, [0-255, default: 5]
	#Range: 0 ~ 255
	gobberOreNetherMinHeight = 5
	#Maximal height for Gobber Nether Ore pocket generation [0-255, default: 255]
	#Range: 0 ~ 255
	gobberOreNetherMaxHeight = 255

#Gobber End Ore Generation
[gobber2_ore_end]
	#Size of Gobber End Ore pockets [0-100, default: 9]
	#Range: 0 ~ 100
	gobberOreEndSize = 9
	#Chances of Gobber End Ore pocket being generated [0-30, default: 15]
	#Range: 0 ~ 30
	gobberOreEndChance = 4
	#Minimal height for Gobber End Ore pocket generation, [0-255, default: 20]
	#Range: 0 ~ 255
	gobberOreEndMinHeight = 20
	#Maximal height for Gobber End Ore pocket generation [0-255, default: 255]
	#Range: 0 ~ 255
	gobberOreEndMaxHeight = 255

#Gobber Tool Material Values
[gobber_tool_material]
	#Gobber tool durability [1-9000, default: 3800]
	#Range: 0 ~ 9000
	gobberToolsDurability = 3800
	#Gobber tool mining speed [1-25, default: 9.0]
	#Range: 1.0 ~ 25.0
	gobberToolsSpeed = 9.0
	#Gobber tool attack damage [1-100, default: 9.0]
	#Range: 1.0 ~ 100.0
	gobberToolsDamage = 9.0
	#Gobber tool enchantability [0-50, default: 20]
	#Range: 1 ~ 50
	gobberToolsEnchantability = 20

#Nether Gobber Tool Material Values
[nether_gobber_tool_material]
	#Nether Gobber tool durability [1-9000, default: 5200]
	#Range: 0 ~ 9000
	netherGobberToolsDurability = 5200
	#Nether Gobber tool mining speed [1-25, default: 12.0]
	#Range: 1.0 ~ 25.0
	netherGobberToolsSpeed = 12.0
	#Nether Gobber tool attack damage [1-100, default: 9.0]
	#Range: 1.0 ~ 100.0
	netherGobberToolsDamage = 9.0
	#Nether Gobber tool enchantability [0-50, default: 25]
	#Range: 1 ~ 50
	netherGobberToolsEnchantability = 25

#End Gobber Tool Material Values
[end_gobber_tool_material]
	#End Gobber tool durability [1-9000, default: 8000]
	#Range: 0 ~ 9000
	endGobberToolsDurability = 8000
	#End Gobber tool mining speed [1-25, default: 14.0]
	#Range: 1.0 ~ 25.0
	endGobberToolsSpeed = 14.0
	#End Gobber tool attack damage [1-100, default: 9.0]
	#Range: 1.0 ~ 100.0
	endGobberToolsDamage = 9.0
	#End Gobber tool enchantability [0-50, default: 30]
	#Range: 1 ~ 50
	endGobberToolsEnchantability = 30
	#Should Tools be unbreakable when crafted? [true / false]
	endGobberToolsUnbreakable = true

#Gobber Armor Material Values
[gobber_armor_material]
	#Gobber armor durability multiplier [1-200, default: 71]
	#Range: 1 ~ 200
	gobberArmorDurabilityMultiplier = 71
	#Gobber armor enchantability [1-50, default: 25]
	#Range: 1 ~ 50
	gobberArmorEnchantability = 25
	#Gobber armor toughness [0-5, default: 2.5]
	#Range: 0.0 ~ 5.0
	gobberArmorToughness = 2.5
	#Gobber armor knockback [0-5, default: 0.1]
	#Range: 0.0 ~ 5.0
	gobberArmorKnockback = 0.1
	#Gobber armor head protection [1-20, default: 6]
	#Range: 1 ~ 20
	gobberHeadProtection = 6
	#Gobber armor chest protection [1-20, default: 11]
	#Range: 1 ~ 20
	gobberChestProtection = 11
	#Gobber armor leggings protection [1-20, default: 9]
	#Range: 1 ~ 20
	gobberLeggingsProtection = 9
	#Gobber armor boots protection [1-20, default: 6]
	#Range: 1 ~ 20
	gobberBootsProtection = 6

#Nether Gobber Armor Material Values
[nether_gobber_armor_material]
	#Nether Gobber armor durability multiplier [1-200, default: 83]
	#Range: 1 ~ 200
	netherGobberArmorDurabilityMultiplier = 83
	#Nether Gobber armor enchantability [1-50, default: 30]
	#Range: 1 ~ 50
	netherGobberArmorEnchantability = 30
	#Nether Gobber armor toughness [0-5, default: 2.75]
	#Range: 0.0 ~ 5.0
	netherGobberArmorToughness = 2.75
	#Nether Gobber armor knockback [0-5, default: 0.1]
	#Range: 0.0 ~ 5.0
	netherGobberArmorKnockback = 0.1
	#Nether armor head protection [1-20, default: 7]
	#Range: 1 ~ 20
	netherHeadProtection = 7
	#Nether armor chest protection [1-20, default: 12]
	#Range: 1 ~ 20
	netherChestProtection = 12
	#Nether armor leggings protection [1-20, default: 10]
	#Range: 1 ~ 20
	netherLeggingsProtection = 10
	#Nether armor boots protection [1-20, default: 7]
	#Range: 1 ~ 20
	netherBootsProtection = 7

#End Gobber Armor Material Values
[end_gobber_armor_material]
	#End Gobber armor durability multiplier [1-200, default: 100]
	#Range: 1 ~ 200
	endGobberArmorDurabilityMultiplier = 100
	#End Gobber armor enchantability [1-50, default: 30]
	#Range: 1 ~ 50
	endGobberArmorEnchantability = 30
	#End Gobber armor toughness [0-5, default: 3.0]
	#Range: 0.0 ~ 5.0
	endGobberArmorToughness = 3.0
	#End Gobber armor knockback [0-5, default: 0.2]
	#Range: 0.0 ~ 5.0
	endGobberArmorKnockback = 0.2
	#Should Armor be unbreakable when crafted? [true / false]
	endGobberArmorUnbreakable = true
	#End armor head protection [1-20, default: 8]
	#Range: 1 ~ 20
	endHeadProtection = 8
	#End armor chest protection [1-20, default: 13]
	#Range: 1 ~ 20
	endChestProtection = 13
	#End armor leggings protection [1-20, default: 11]
	#Range: 1 ~ 20
	endLeggingsProtection = 11
	#End armor boots protection [1-20, default: 8]
	#Range: 1 ~ 20
	endBootsProtection = 8

#Dragon Armor Material Values
[dragon_armor_material]
	#Dragon armor durability multiplier [1-200, default: 100]
	#Range: 1 ~ 200
	dragonArmorDurabilityMultiplier = 100
	#Dragon armor enchantability [1-50, default: 30]
	#Range: 1 ~ 50
	dragonArmorEnchantability = 30
	#Dragon armor toughness [0-5, default: 3.0]
	#Range: 0.0 ~ 5.0
	dragonArmorToughness = 3.0
	#Dragon armor knockback [0-5, default: 0.3]
	#Range: 0.0 ~ 5.0
	dragonArmorKnockback = 0.3
	#Should Armor be unbreakable when crafted? [true / false]
	dragonArmorUnbreakable = true
	#Dragon armor head protection [1-20, default: 8]
	#Range: 1 ~ 20
	dragonHeadProtection = 8
	#Dragon armor chest protection [1-20, default: 13]
	#Range: 1 ~ 20
	dragonChestProtection = 13
	#Dragon armor leggings protection [1-20, default: 11]
	#Range: 1 ~ 20
	dragonLeggingsProtection = 11
	#Dragon armor boots protection [1-20, default: 8]
	#Range: 1 ~ 20
	dragonBootsProtection = 8

#Armor Health Perks Settings
[armor_health_perk_settings]
	#Enable/disable Gobber Armor No Fall Damage
	gobberArmorNoFallDamage = true
	#Enable/disable Gobber Armor fire protection
	gobberArmorFireProtection = true
	#Enable/disable Gobber Armor water breathing
	gobberArmorWaterBreathing = true
	#Enable/disable Gobber Armor health perks
	gobberArmorHealthPerks = true
	#Enable/disable Gobber Nether Armor health perks
	gobberNetherArmorHealthPerks = true
	#Enable/disable Gobber End Armor health perks
	gobberEndArmorHealthPerks = true
	#Enable/disable Gobber Dragon Armor health perks
	gobberDragonArmorHealthPerks = true
	#Enable/disable Gobber Armor auto feeding
	gobberArmorAutofeed = true
	#Enable/disable Gobber Nether Armor auto feeding
	gobberNetherArmorAutofeed = true
	#Enable/disable Gobber End Armor auto feeding
	gobberEndArmorAutofeed = true
	#Enable/disable Gobber Dragon Armor auto feeding
	gobberDragonArmorAutofeed = true
	#Enable/disable Gobber Dragon Armor flight
	gobberDragonArmorFlight = true
	#Enable/disable Gobber Nether Armor yellow hearts perks
	gobberNetherArmorYellowHeartsPerks = true
	#Enable/disable Gobber End Armor yellow hearts perks
	gobberEndArmorYellowHeartsPerks = true
	#Enable/disable Gobber Dragon Armor yellow hearts perks
	gobberDragonArmorYellowHeartsPerks = true

#Gobber Food Values
[gobber_foods]
	#Goo hunger value [0-25, default: 7]
	#Range: 0 ~ 25
	gooHunger = 4
	#Goo saturation value [0-5, default: 0.7]
	#Range: 0.0 ~ 5.0
	gooSaturation = 0.7
	#Gooey apple hunger value [0-25, default: 8]
	#Range: 0 ~ 25
	gooeyAppleHunger = 5
	#Gooey apple saturation value [0-5, default: 0.8]
	#Range: 0.0 ~ 5.0
	gooeyAppleSaturation = 0.8
	#Gooey bread hunger value [0-25, default: 8]
	#Range: 0 ~ 25
	gooeyBreadHunger = 5
	#Gooey bread saturation value [0-5, default: 0.8]
	#Range: 0.0 ~ 5.0
	gooeyBreadSaturation = 0.8
	#Gooey beef hunger value [0-25, default: 9]
	#Range: 0 ~ 25
	gooeyBeefHunger = 6
	#Gooey beef saturation value [0-5, default: 0.9]
	#Range: 0.0 ~ 5.0
	gooeyBeefSaturation = 0.9
	#Gooey beefstew hunger value [0-25, default: 10]
	#Range: 0 ~ 25
	gooeyBeefstewHunger = 7
	#Gooey beefstew saturation value [0-5, default: 1.0]
	#Range: 0.0 ~ 5.0
	gooeyBeefstewSaturation = 1.0

#Nether Gobber Food Values
[nether_gobber_foods]
	#Nether Goo hunger value [0-25, default: 7]
	#Range: 0 ~ 25
	netherGooHunger = 7
	#Nether Goo saturation value [0-5, default: 0.7]
	#Range: 0.0 ~ 5.0
	netherGooSaturation = 0.9
	#Nether Gooey apple hunger value [0-25, default: 8]
	#Range: 0 ~ 25
	netherGooeyAppleHunger = 8
	#Nether Gooey apple saturation value [0-5, default: 0.8]
	#Range: 0.0 ~ 5.0
	netherGooeyAppleSaturation = 1.0
	#Nether Gooey bread hunger value [0-25, default: 8]
	#Range: 0 ~ 25
	netherGooeyBreadHunger = 9
	#Nether Gooey bread saturation value [0-5, default: 0.8]
	#Range: 0.0 ~ 5.0
	netherGooeyBreadSaturation = 1.0
	#Nether Gooey beef hunger value [0-25, default: 9]
	#Range: 0 ~ 25
	netherGooeyBeefHunger = 10
	#Nether Gooey beef saturation value [0-5, default: 0.9]
	#Range: 0.0 ~ 5.0
	netherGooeyBeefSaturation = 1.2
	#Nether Gooey beefstew hunger value [0-25, default: 10]
	#Range: 0 ~ 25
	netherGooeyBeefstewHunger = 11
	#Nether Gooey beefstew saturation value [0-5, default: 1.0]
	#Range: 0.0 ~ 5.0
	netherGooeyBeefstewSaturation = 1.5

#Item Cooldown Settings
[item_cooldown_settings]
	#Number of ticks duration for the Ring of Blink cooldown [0-3600, default: 60]
	#Range: 0 ~ 3600
	ringBlinkCooldown = 60
	#Number of ticks duration for the Ring of the Miner cooldown [0-3600, default: 80]
	#Range: 0 ~ 3600
	ringMinerCooldown = 80
	#Number of ticks duration for the Ring of Above cooldown [0-3600, default: 80]
	#Range: 0 ~ 3600
	ringAboveCooldown = 80
	#Number of ticks duration for the Ring of the Explorer cooldown [0-3600, default: 480]
	#Range: 0 ~ 3600
	ringExplorerCooldown = 480
	#Number of ticks duration for the Sword of the Sniper cooldown [0-3600, default: 60]
	#Range: 0 ~ 3600
	swordSniperCooldown = 60
	#Number of ticks duration for the Staff of the Sniper cooldown [0-3600, default: 60]
	#Range: 0 ~ 3600
	staffSniperCooldown = 60
	#Number of ticks duration for the Ring of Husbandry cooldown [0-9600, default: 2400]
	#Range: 0 ~ 9600
	ringHusbandryCooldown = 2400

#Ring of the Explorer Settings
[ring_explorer_settings]
	#Ring of Explorer - Min distance from world spawn to begin searching for a spot [default: 500]
	#Range: 0 ~ 100000
	ringExplorerMin = 500
	#Ring of Explorer - Max distance from world spawn to begin searching for a spot [default: 6000]
	#Range: 0 ~ 250000
	ringExplorerMax = 6000

#Misc Ring/staff Settings
[misc_ring_staff_settings]
	#Reverse the drop/no drops feature on Ring of Miner [true / false]
	reverseRingMiner = false
	#Uses a delayed break mode to reduce stutter and potential lag on Ring of Miner and Ring of Lumberjack [true / false]
	delayedBreakMode = true
	#Ring of Acceleration - amount of velocity applied [default: .18]
	#Range: 0.0 ~ 0.3
	ringAccelerationVelocity = 0.18
	#Ring of Repair - Delay time between repair ticks [default: 120]
	#Range: 20 ~ 600
	ringRepairDelay = 120
	#Ring of Attraction - Distance coal blocks magnet effect [default: 5]
	#Range: 0 ~ 15
	ringAttractionBlocking = 5
	#Ring of Attraction - Items are instantly placed in player inventory  [true / false]
	ringAttractionMode = false
	#Ring of Dismissal - Sets the horizontal velocity [default: 0.2]
	#Range: 0.0 ~ 15.0
	ringDismissalVelocity = 0.2
	#Ring of Dismissal - Sets the horizontal range to detect mobs [default: 8.0]
	#Range: 0.0 ~ 16.0
	ringDismissalLift = 8.0
	#Enable a single use of the Ring of Teleport [true / false]
	limitedUseRingTeleport = false

#Ring/Staff of Farmer Settings
[farmer_settings]
	#Ring of the Farmer base tick delay [default: 20]
	#Range: 10 ~ 120
	ringFarmerTickDelay = 20
	#Ring of the Farmer radius from player [default: 10]
	#Range: 2 ~ 20
	ringFarmerRadius = 10
	#Staff of the Farmer base tick delay [default: 20]
	#Range: 10 ~ 120
	staffFarmerTickDelay = 20
	#Staff of the Farmer radius from player [default: 10]
	#Range: 2 ~ 20
	staffFarmerRadius = 10

#Auto Replanting Settings
[replanting_settings]
	#Should the Staff of Harvest auto-replant? [true / false]
	StaffHarvestReplant = true
	#Should the Staff of the Farmer auto-replant? [true / false]
	StaffFarmerReplant = true

#Armor Hunger/Saturation Settings
[armor_health_settings]
	#Amount of hunger point to restore per interval
	#Range: 0 ~ 10
	gobberArmorHunger = 4
	#Amount of saturation point to restore per interval
	#Range: 0.0 ~ 10.0
	gobberArmorSaturation = 0.02
	#Amount of hunger point to restore per interval
	#Range: 0 ~ 10
	gobberNetherArmorHunger = 1
	#Amount of saturation point to restore per interval
	#Range: 0.0 ~ 10.0
	gobberNetherArmorSaturation = 0.05
	#Amount of hunger point to restore per interval
	#Range: 0 ~ 10
	gobberEndArmorHunger = 1
	#Amount of saturation point to restore per interval
	#Range: 0.0 ~ 10.0
	gobberEndArmorSaturation = 0.1
	#Amount of hunger point to restore per interval
	#Range: 0 ~ 10
	gobberDragonArmorHunger = 1
	#Amount of saturation point to restore per interval
	#Range: 0.0 ~ 10.0
	gobberDragonArmorSaturation = 0.15

#Medallion of Experience Settings
[medallion_exp_settings]
	#Medallion of Experience multiplier for extra XP orbs [default: 5]
	#Range: 0 ~ 20
	medallionExpOrbs = 5
	#Medallion of Experience multiplier for extra mob loot [default: 20]
	#Range: 5 ~ 100
	medallionExpLoot = 20

#Dragon Star Special
[dragonStar_special]
	#Enable Dragon Star Offhannd Function [true / false]
	enableDragonStarOffhand = true

#Enable Dragon Armor Void Protect - immune to /kill command
[dragon_armor_void]
	#Enable Dragon Armor Void Protection [true / false]
	enableDragonArmorVoidProtection = false

#Dragon Egg With Every Kill
[dragon_egg_kill]
	#Enable Dragon Egg drops on every kill [true / false]
	enableDragonEggEveryKill = true

